//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveCoursesBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public long Id { get; set; }
        public int Nr { get; set; }
        public string Name { get; set; }
        public string HtmlContent { get; set; }
        public long CourseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
